# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/davidcox/Repositories/monkeyworks/mw_supporting/boost_1_40_0/libs/xpressive/CMakeLists.txt
	/opt/local/bin/cmake -H/Users/davidcox/Repositories/monkeyworks/mw_supporting/boost_1_40_0 -B/Users/davidcox/Repositories/monkeyworks/mw_supporting/boost_1_40_0
